name: LD2450 Zone Configurator
version: "1.0.0"
slug: ld2450_zone_configurator
description: A Home Assistant add-on to configure zones for the HLK-LD2450 mmWave sensor
url: "https://example.com"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web interface for zone configuration
options:
  ha_api_url: "http://homeassistant.local:8123"
  ha_api_token: ""
schema:
  ha_api_url: str
  ha_api_token: str